---
vector_url: https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm
vector_version: 0.21.1
vector_config:
  sources:
    our_log:
      type: file
      ignore_older_secs: 600
      include: 
        - home/ilya/logs/*.log"
      read_from: beginning
  sinks:
    to_clickhouse:
      type: clickhouse
      inputs:
        - our_log
      database: logs
      endpoint: http://51.250.64.225:8123
      table: my_table
      compression: gzip
      healthcheck: false
      skip_unknown_fields: true